# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pact < Formula
  desc "Pact CLI - Sync your dotfiles and configurations"
  homepage "https://github.com/cloudboy-jh/pact"
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudboy-jh/pact/releases/download/v0.1.9/pact_0.1.9_darwin_amd64.tar.gz"
      sha256 "4a71326f9a4e5465278821557d5d34631806d123d93d5a3113c182b8dc01e5bf"

      def install
        bin.install "pact"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudboy-jh/pact/releases/download/v0.1.9/pact_0.1.9_darwin_arm64.tar.gz"
      sha256 "2eb912eb449dc5ed78f4df4ac136e6e83479b17bbce9aed32c9b98ec3fd17b1c"

      def install
        bin.install "pact"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudboy-jh/pact/releases/download/v0.1.9/pact_0.1.9_linux_amd64.tar.gz"
      sha256 "d3a0043a490ec78b19656a25c4c5ea4606bfe148530ad57ddf1dec9ed084979f"
      def install
        bin.install "pact"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudboy-jh/pact/releases/download/v0.1.9/pact_0.1.9_linux_arm64.tar.gz"
      sha256 "495bc4a64e0e503dd3eff506d748089e48c4fb4e81656cfed4ae1280f4db2430"
      def install
        bin.install "pact"
      end
    end
  end

  test do
    system "#{bin}/pact", "--help"
  end
end
