# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pact < Formula
  desc "Pact CLI - Sync your dotfiles and configurations"
  homepage "https://github.com/cloudboy-jh/pact"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudboy-jh/pact/releases/download/v0.1.8/pact_0.1.8_darwin_amd64.tar.gz"
      sha256 "320de463a5b687b241e1396cf35bf4480a16084f5067afdc5a6d9f08f131d752"

      def install
        bin.install "pact"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudboy-jh/pact/releases/download/v0.1.8/pact_0.1.8_darwin_arm64.tar.gz"
      sha256 "7fa819deec218f9a5c80c5f146eaec264a7798558f5c8c906a66889f3f965ec1"

      def install
        bin.install "pact"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudboy-jh/pact/releases/download/v0.1.8/pact_0.1.8_linux_amd64.tar.gz"
      sha256 "81ba408091e284caf9ad3337885a152d34da772059b82a415dac4f8ba87af852"
      def install
        bin.install "pact"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudboy-jh/pact/releases/download/v0.1.8/pact_0.1.8_linux_arm64.tar.gz"
      sha256 "8178b0052586d4d6399ef4b1b8551d9c05094be795b9f8b3ab7837b161f76907"
      def install
        bin.install "pact"
      end
    end
  end

  test do
    system "#{bin}/pact", "--help"
  end
end
