# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pact < Formula
  desc "Pact CLI - Sync your dotfiles and configurations"
  homepage "https://github.com/cloudboy-jh/pact"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudboy-jh/pact/releases/download/v0.1.4/pact_0.1.4_darwin_amd64.tar.gz"
      sha256 "7e48ba59444cbfe0e063c8b56252f848d2bebaa304787ad667fc406b07a88daa"

      def install
        bin.install "pact"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudboy-jh/pact/releases/download/v0.1.4/pact_0.1.4_darwin_arm64.tar.gz"
      sha256 "80d95f9c40facc3557bf6c255b7fb83e6b3bd8c1c62fce101e5b5dc9604a0877"

      def install
        bin.install "pact"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudboy-jh/pact/releases/download/v0.1.4/pact_0.1.4_linux_amd64.tar.gz"
      sha256 "2b7147cccbac6f6a8f922b2112bf7e22df01eb6ef0ebbccfc6687f0a3329da03"
      def install
        bin.install "pact"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudboy-jh/pact/releases/download/v0.1.4/pact_0.1.4_linux_arm64.tar.gz"
      sha256 "15f19948063b31fa1eea45f1bed524472239284bee0b1632a7e0571fb55bc517"
      def install
        bin.install "pact"
      end
    end
  end

  test do
    system "#{bin}/pact", "--help"
  end
end
